[mypy]
ignore_missing_imports = True
follow_imports = skip
check_untyped_defs = False
disable_error_code =
    annotation-unchecked,
    arg-type,
    assignment,
    attr-defined,
    call-arg,
    dict-item,
    has-type,
    import-not-found,
    import-untyped,
    index,
    list-item,
    method-assign,
    misc,
    no-any-return,
    no-untyped-def,
    operator,
    return-value,
    str-bytes-safe,
    union-attr,
    var-annotated

