// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 hipfire contributors
// hipfire — see LICENSE and NOTICE in the project root.

//! DFlash2 drafter math: grouped dynamic causal convolution + candidate
//! selector. CPU reference, ported from z-lab/dflash `dflash/model.py`
//! (`_grouped_dynamic_convolve`, `GroupedDynamicCausalConv`,
//! `CandidateSelector`), and checked against golden vectors generated by that
//! reference against the real checkpoint weights — see
//! `examples/dflash2_parity.rs`.
//!
//! These are the semantics the GPU kernels must reproduce. Two things are easy
//! to get wrong from the tensor shapes alone, and both were:
//!
//!  * `base_kernel` is `[2, kernel_size, hidden]`. The leading 2 is NOT the tap
//!    count — it is TWO conv passes, `prepare()` before the attention/MLP block
//!    and `finish()` after, fed by slices `[..,0,:,:]` and `[..,1,:,:]` of the
//!    projection output.
//!  * the dynamic coefficient is per (position, tap, GROUP) — one scalar per
//!    `group_size` channels — and is ADDED to a static per-channel base kernel,
//!    both multiplying the same causally shifted input.

/// One conv pass. `hidden` is `[len, hidden_size]` row-major, `dynamic` is
/// `[len, kernel_size, groups]`, `base` is `[kernel_size, hidden_size]`.
///
/// `out[t, c] = Σ_tap (base[tap, c] + dynamic[t, tap, group_of(c)]) · h[t-tap, c]`
/// with `h[<0] = 0` (causal, zero-padded at the front).
pub fn grouped_dynamic_convolve(
    hidden: &[f32],
    dynamic: &[f32],
    base: &[f32],
    len: usize,
    hidden_size: usize,
    kernel_size: usize,
    group_size: usize,
) -> Vec<f32> {
    let groups = hidden_size / group_size;
    let mut out = vec![0f32; len * hidden_size];
    for t in 0..len {
        for tap in 0..kernel_size {
            // Causal shift: tap 0 is the current position, tap k reads t-k.
            if t < tap {
                continue;
            }
            let src = (t - tap) * hidden_size;
            let dyn_row = (t * kernel_size + tap) * groups;
            for c in 0..hidden_size {
                let v = hidden[src + c];
                let k = base[tap * hidden_size + c] + dynamic[dyn_row + c / group_size];
                out[t * hidden_size + c] += k * v;
            }
        }
    }
    out
}

/// Candidate-selector transition scores for ONE position.
///
/// `score[k] = unary[k] + Σ_r predecessor[r] · hidden_proj[r] · successor[k, r]`
///
/// The predecessor codebook row is gated ELEMENTWISE by the projected hidden,
/// then dotted against each candidate's successor row — a rank-`rank` triple
/// product, not a plain bilinear form.
pub fn selector_scores(
    unary: &[f32],
    predecessor: &[f32],
    hidden_proj: &[f32],
    successor: &[f32],
    top_k: usize,
    rank: usize,
) -> Vec<f32> {
    let gated: Vec<f32> = (0..rank).map(|r| predecessor[r] * hidden_proj[r]).collect();
    (0..top_k)
        .map(|k| {
            let row = &successor[k * rank..(k + 1) * rank];
            unary[k] + gated.iter().zip(row).map(|(g, s)| g * s).sum::<f32>()
        })
        .collect()
}

/// Greedy left-to-right path trace. NOT Viterbi — the reference takes an argmax
/// per position with no backtracking, and each pick seeds the next predecessor.
pub fn selector_argmax(scores: &[f32]) -> usize {
    let mut best = 0;
    for i in 1..scores.len() {
        if scores[i] > scores[best] {
            best = i;
        }
    }
    best
}
