// SPDX-License-Identifier: Apache-2.0
// @generated by `hipfire gen-model-support` from docs/model-support.toml.
// DO NOT EDIT BY HAND — edit the .toml and regenerate.
#![allow(dead_code)]

use crate::{ArchFeatures, FeatureSupport};

/// One row of the per-arch capability matrix.
pub struct ArchRow {
    pub ids: &'static [u32],
    pub features: ArchFeatures,
}

/// Per-arch capabilities, keyed by HFQ arch_id (see `arch_features`).
pub const ARCH_ROWS: &[ArchRow] = &[
    ArchRow {
        ids: &[5, 6],
        features: ArchFeatures {
            label: "qwen3.5",
            prefill: FeatureSupport::Full,
            dflash: FeatureSupport::Full,
            mtp: FeatureSupport::Full,
            kv: "full",
            vision: FeatureSupport::Partial,
        },
    },
    ArchRow {
        ids: &[9],
        features: ArchFeatures {
            label: "deepseek4",
            prefill: FeatureSupport::Full,
            dflash: FeatureSupport::None,
            mtp: FeatureSupport::Partial,
            kv: "fp32",
            vision: FeatureSupport::None,
        },
    },
    ArchRow {
        ids: &[10],
        features: ArchFeatures {
            label: "minimax",
            prefill: FeatureSupport::Partial,
            dflash: FeatureSupport::None,
            mtp: FeatureSupport::Partial,
            kv: "fp32",
            vision: FeatureSupport::None,
        },
    },
    ArchRow {
        ids: &[11],
        features: ArchFeatures {
            label: "lfm2-moe",
            prefill: FeatureSupport::Partial,
            dflash: FeatureSupport::None,
            mtp: FeatureSupport::None,
            kv: "fp32",
            vision: FeatureSupport::None,
        },
    },
    ArchRow {
        ids: &[12],
        features: ArchFeatures {
            label: "gemma3",
            prefill: FeatureSupport::Full,
            dflash: FeatureSupport::None,
            mtp: FeatureSupport::None,
            kv: "fp32+q8",
            vision: FeatureSupport::None,
        },
    },
    ArchRow {
        ids: &[13],
        features: ArchFeatures {
            label: "gemma3-vl",
            prefill: FeatureSupport::Full,
            dflash: FeatureSupport::None,
            mtp: FeatureSupport::None,
            kv: "fp32+q8",
            vision: FeatureSupport::Full,
        },
    },
    ArchRow {
        ids: &[7],
        features: ArchFeatures {
            label: "qwen2",
            prefill: FeatureSupport::Full,
            dflash: FeatureSupport::None,
            mtp: FeatureSupport::None,
            kv: "fp32",
            vision: FeatureSupport::None,
        },
    },
    ArchRow {
        ids: &[8],
        features: ArchFeatures {
            label: "dots-ocr",
            prefill: FeatureSupport::Full,
            dflash: FeatureSupport::None,
            mtp: FeatureSupport::None,
            kv: "fp32",
            vision: FeatureSupport::Full,
        },
    },
    ArchRow {
        ids: &[0, 1],
        features: ArchFeatures {
            label: "llama",
            prefill: FeatureSupport::Partial,
            dflash: FeatureSupport::None,
            mtp: FeatureSupport::None,
            kv: "fp32",
            vision: FeatureSupport::None,
        },
    },
];

/// A quant format and its weight/activation bit-width + maturity.
pub struct QuantInfo {
    pub name: &'static str,
    pub label: &'static str,
    pub weight_bits: u32,
    pub act_bits: u32,
    pub status: &'static str,
}

pub const QUANT_TABLE: &[QuantInfo] = &[
    QuantInfo {
        name: "bf16",
        label: "BF16 (unquantized)",
        weight_bits: 16,
        act_bits: 16,
        status: "stable",
    },
    QuantInfo {
        name: "q8",
        label: "Q8 (W8A16)",
        weight_bits: 8,
        act_bits: 16,
        status: "stable",
    },
    QuantInfo {
        name: "mq4",
        label: "Magnum / MQ4 (W4A16)",
        weight_bits: 4,
        act_bits: 16,
        status: "stable",
    },
    QuantInfo {
        name: "mq6",
        label: "Magnum / MQ6 (W6A16)",
        weight_bits: 6,
        act_bits: 16,
        status: "stable",
    },
    QuantInfo {
        name: "oq4",
        label: "Opus Quant / OQ4 (4-bit-resident; W4A16 decode, W4A4 batched prefill)",
        weight_bits: 4,
        act_bits: 4,
        status: "opt-in",
    },
    QuantInfo {
        name: "oq8",
        label: "Opus Quant / OQ8",
        weight_bits: 4,
        act_bits: 8,
        status: "opt-in",
    },
    QuantInfo {
        name: "mq3",
        label: "Magnum / MQ3 (W3A16, mixed-precision only)",
        weight_bits: 3,
        act_bits: 16,
        status: "experimental",
    },
];

/// An intentional (arch × quant × feature) override of the arch-level
/// capability — the per-quant axis the arch matrix can't express.
pub struct GateRow {
    pub arch: u32,
    pub quant: &'static str,
    pub feature: &'static str,
    pub support: FeatureSupport,
    pub note: &'static str,
}

pub const GATE_TABLE: &[GateRow] = &[
    GateRow {
        arch: 5,
        quant: "oq4",
        feature: "prefill",
        support: FeatureSupport::Partial,
        note: "W4A4 (OQ4) batched prefill is parity-gated / opt-in (HIPFIRE WMMA path)",
    },
    GateRow {
        arch: 5,
        quant: "oq8",
        feature: "prefill",
        support: FeatureSupport::Partial,
        note: "W8A8 (OQ8) batched-prefill WMMA path is experimental / parity-gated",
    },
];
