//! AIE2P 4x4 whole-array W4A8/W8A8 GEMM with two-dimensional operand reuse.
//!
//! The generated R14 schedule broadcasts four 24-row activation stripes
//! horizontally and four 96-column weight stripes vertically. One dispatch
//! covers all padded M/N macro tiles and every K=256 Opus group; returned int32
//! partials remain group-major so the caller can apply arbitrary group scales.
#![cfg(target_os = "linux")]

use std::collections::HashMap;

use crate::{DeviceBuffer, NpuKernel, XdnaError};

const ARRAY: usize = 4;
const OUT_N: usize = 16;
const GROUP_K: usize = 256;

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum NpuWholeMode {
    W4,
    W8,
}

#[derive(Clone, Copy)]
struct Layout {
    mode: NpuWholeMode,
    lm: usize,
    ln: usize,
    mr: usize,
    inner_k: usize,
    weight_bytes: usize,
}

impl Layout {
    fn for_mode(mode: NpuWholeMode) -> Self {
        match mode {
            NpuWholeMode::W4 => Self {
                mode,
                lm: 6,
                ln: 6,
                mr: 4,
                inner_k: 16,
                weight_bytes: 6 * GROUP_K * OUT_N / 2,
            },
            NpuWholeMode::W8 => Self {
                mode,
                lm: 3,
                ln: 3,
                mr: 8,
                inner_k: 8,
                weight_bytes: 3 * GROUP_K * OUT_N,
            },
        }
    }

    fn rows_per_stripe(self) -> usize {
        self.lm * self.mr
    }

    fn macro_m(self) -> usize {
        ARRAY * self.rows_per_stripe()
    }

    fn cols_per_stripe(self) -> usize {
        self.ln * OUT_N
    }

    fn macro_n(self) -> usize {
        ARRAY * self.cols_per_stripe()
    }

    fn activation_bytes(self) -> usize {
        self.rows_per_stripe() * GROUP_K
    }

    fn output_per_core(self) -> usize {
        self.lm * self.ln * self.mr * OUT_N
    }

    fn output_join(self) -> usize {
        ARRAY * self.output_per_core()
    }
}

/// Device-resident R14 weight streams for one complete matrix.
pub struct NpuWholeResidentWeights {
    buffer: DeviceBuffer,
}

/// Reusable argument buffers and a generated whole-array AIE2P schedule.
pub struct NpuGemmWholeArray {
    kernel: NpuKernel,
    layout: Layout,
    rows: usize,
    groups: usize,
    n: usize,
    m_macros: usize,
    n_macros: usize,
    blocks: usize,
    input: DeviceBuffer,
    output: DeviceBuffer,
}

impl NpuGemmWholeArray {
    /// Load a cache generated by `r14_aie2p_cache.sh`. Geometry is read from
    /// `shape.txt` instead of inferred from buffer sizes or stale defaults.
    pub fn load_cached(dir: &str) -> Result<Self, XdnaError> {
        let shape_text =
            std::fs::read_to_string(format!("{dir}/shape.txt")).map_err(XdnaError::Open)?;
        let shape = parse_shape(&shape_text);
        let mode = match shape_text
            .lines()
            .find_map(|line| line.strip_prefix("mode="))
        {
            Some("w4") | None => NpuWholeMode::W4,
            Some("w8") => NpuWholeMode::W8,
            Some(other) => return Err(invalid(format!("unsupported whole-array mode {other}"))),
        };
        let layout = Layout::for_mode(mode);
        let rows = required(&shape, "m", dir)?;
        let k = required(&shape, "k", dir)?;
        let n = required(&shape, "n", dir)?;
        let lm = shape.get("lm").copied().unwrap_or(layout.lm);
        let ln = shape.get("ln").copied().unwrap_or(layout.ln);
        let m_macros = required(&shape, "mm", dir)?;
        let n_macros = required(&shape, "nm", dir)?;
        let groups = required(&shape, "kg", dir)?;
        let blocks = required(&shape, "nblk", dir)?;
        if rows == 0
            || n == 0
            || k != groups * GROUP_K
            || lm != layout.lm
            || ln != layout.ln
            || m_macros != rows.div_ceil(layout.macro_m())
            || n_macros != n.div_ceil(layout.macro_n())
            || blocks != m_macros * n_macros * groups
        {
            return Err(invalid(format!(
                "invalid whole-array cache geometry in {dir}"
            )));
        }

        let xclbin = std::fs::read(format!("{dir}/final.xclbin")).map_err(XdnaError::Open)?;
        let instructions = std::fs::read(format!("{dir}/insts.bin")).map_err(XdnaError::Open)?;
        let kernel = NpuKernel::load(&xclbin, &instructions)?;
        let input = kernel.alloc_arg(ARRAY * blocks * layout.activation_bytes())?;
        let output = kernel.alloc_arg(ARRAY * blocks * layout.output_join() * size_of::<i32>())?;
        Ok(Self {
            kernel,
            layout,
            rows,
            groups,
            n,
            m_macros,
            n_macros,
            blocks,
            input,
            output,
        })
    }

    pub fn rows(&self) -> usize {
        self.rows
    }

    pub fn mode(&self) -> NpuWholeMode {
        self.layout.mode
    }

    pub fn k(&self) -> usize {
        self.groups * GROUP_K
    }

    pub fn n(&self) -> usize {
        self.n
    }

    pub fn packed_weight_bytes(&self) -> usize {
        ARRAY * self.blocks * self.layout.weight_bytes
    }

    /// Pack row-major `[256,N]` matrices into the four column-broadcast
    /// streams. Padded N columns are zero; weights are duplicated only across
    /// distinct M macro tiles because the generated stream consumes one W
    /// stripe for every complete `(M-macro,N-macro,K-group)` block.
    pub fn prepack_weights(&self, weights: &[&[i8]]) -> Result<Vec<u8>, XdnaError> {
        if weights.len() != self.groups
            || weights.iter().any(|group| group.len() != GROUP_K * self.n)
        {
            return Err(invalid("whole-array weight group geometry mismatch"));
        }
        let mut packed = vec![0u8; self.packed_weight_bytes()];
        for stripe in 0..ARRAY {
            for m_macro in 0..self.m_macros {
                for n_macro in 0..self.n_macros {
                    for (group, matrix) in weights.iter().enumerate() {
                        let block = self.block(m_macro, n_macro, group);
                        let stripe_start =
                            (stripe * self.blocks + block) * self.layout.weight_bytes;
                        let output =
                            &mut packed[stripe_start..stripe_start + self.layout.weight_bytes];
                        for ln in 0..self.layout.ln {
                            for kt in 0..GROUP_K / self.layout.inner_k {
                                for kk in 0..self.layout.inner_k {
                                    for nn in 0..OUT_N {
                                        let col = n_macro * self.layout.macro_n()
                                            + stripe * self.layout.cols_per_stripe()
                                            + ln * OUT_N
                                            + nn;
                                        let value = if col < self.n {
                                            matrix[(kt * self.layout.inner_k + kk) * self.n + col]
                                        } else {
                                            0
                                        };
                                        match self.layout.mode {
                                            NpuWholeMode::W4 => {
                                                let index = (ln * (GROUP_K / self.layout.inner_k)
                                                    + kt)
                                                    * self.layout.inner_k
                                                    * OUT_N
                                                    + kk * OUT_N
                                                    + nn;
                                                if !(-8..=7).contains(&value) {
                                                    return Err(invalid(format!(
                                                        "W4 value {value} outside -8..=7"
                                                    )));
                                                }
                                                let nibble = (value & 0x0f) as u8;
                                                output[index / 2] |= if index % 2 == 0 {
                                                    nibble
                                                } else {
                                                    nibble << 4
                                                };
                                            }
                                            NpuWholeMode::W8 => {
                                                let index = (ln * (GROUP_K / self.layout.inner_k)
                                                    + kt)
                                                    * self.layout.inner_k
                                                    * OUT_N
                                                    + (nn / 8) * 64
                                                    + kk * 8
                                                    + nn % 8;
                                                output[index] = value as u8;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        Ok(packed)
    }

    pub fn upload_resident_weights(
        &self,
        packed: &[u8],
    ) -> Result<NpuWholeResidentWeights, XdnaError> {
        if packed.len() != self.packed_weight_bytes() {
            return Err(invalid(format!(
                "whole-array weights want {} bytes, got {}",
                self.packed_weight_bytes(),
                packed.len()
            )));
        }
        let mut buffer = self.kernel.alloc_arg(packed.len())?;
        buffer.as_mut_slice().copy_from_slice(packed);
        self.kernel.sync_to_device(&buffer)?;
        Ok(NpuWholeResidentWeights { buffer })
    }

    /// Run a complete projection. Activations are row-major `[M,K]`; partials
    /// are group-major `[K/256,M,N]`. M/N tail cells exist only in the device
    /// streams and are discarded during readback.
    pub fn run_resident(
        &mut self,
        weights: &NpuWholeResidentWeights,
        activations: &[i8],
        partials: &mut [i32],
    ) -> Result<(), XdnaError> {
        if activations.len() != self.rows * self.k()
            || partials.len() != self.groups * self.rows * self.n
            || weights.buffer.len() != self.packed_weight_bytes()
        {
            return Err(invalid("whole-array activation/output geometry mismatch"));
        }
        self.pack_activations(activations);
        self.kernel.dispatch_synced(
            &[&self.input, &weights.buffer, &self.output],
            &[true, false, false],
        )?;
        self.unpack_output(partials);
        Ok(())
    }

    fn block(&self, m_macro: usize, n_macro: usize, group: usize) -> usize {
        (m_macro * self.n_macros + n_macro) * self.groups + group
    }

    fn pack_activations(&mut self, activations: &[i8]) {
        self.input.as_mut_slice().fill(0);
        for stripe in 0..ARRAY {
            for m_macro in 0..self.m_macros {
                for n_macro in 0..self.n_macros {
                    for group in 0..self.groups {
                        let block = self.block(m_macro, n_macro, group);
                        let destination =
                            (stripe * self.blocks + block) * self.layout.activation_bytes();
                        for lm in 0..self.layout.lm {
                            for kt in 0..GROUP_K / self.layout.inner_k {
                                for local_row in 0..self.layout.mr {
                                    let row = m_macro * self.layout.macro_m()
                                        + stripe * self.layout.rows_per_stripe()
                                        + lm * self.layout.mr
                                        + local_row;
                                    if row >= self.rows {
                                        continue;
                                    }
                                    let source =
                                        row * self.k() + group * GROUP_K + kt * self.layout.inner_k;
                                    let target = destination
                                        + (lm * (GROUP_K / self.layout.inner_k) + kt)
                                            * self.layout.mr
                                            * self.layout.inner_k
                                        + local_row * self.layout.inner_k;
                                    self.input.as_mut_slice()[target..target + self.layout.inner_k]
                                        .copy_from_slice(as_bytes(
                                            &activations[source..source + self.layout.inner_k],
                                        ));
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    fn unpack_output(&self, partials: &mut [i32]) {
        let physical = as_i32(self.output.as_slice());
        for column in 0..ARRAY {
            for m_macro in 0..self.m_macros {
                for n_macro in 0..self.n_macros {
                    for group in 0..self.groups {
                        let block = self.block(m_macro, n_macro, group);
                        for row_stripe in 0..ARRAY {
                            let core = (column * self.blocks + block) * self.layout.output_join()
                                + row_stripe * self.layout.output_per_core();
                            for lm in 0..self.layout.lm {
                                for ln in 0..self.layout.ln {
                                    for local_row in 0..self.layout.mr {
                                        let row = m_macro * self.layout.macro_m()
                                            + row_stripe * self.layout.rows_per_stripe()
                                            + lm * self.layout.mr
                                            + local_row;
                                        if row >= self.rows {
                                            continue;
                                        }
                                        for col16 in 0..OUT_N {
                                            let col = n_macro * self.layout.macro_n()
                                                + column * self.layout.cols_per_stripe()
                                                + ln * OUT_N
                                                + col16;
                                            if col >= self.n {
                                                continue;
                                            }
                                            let source = core
                                                + (lm * self.layout.ln + ln)
                                                    * self.layout.mr
                                                    * OUT_N
                                                + local_row * OUT_N
                                                + col16;
                                            partials[(group * self.rows + row) * self.n + col] =
                                                physical[source];
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

fn parse_shape(contents: &str) -> HashMap<&str, usize> {
    contents
        .lines()
        .filter_map(|line| {
            let (key, value) = line.split_once('=')?;
            Some((key, value.parse().ok()?))
        })
        .collect()
}

fn required(shape: &HashMap<&str, usize>, key: &str, dir: &str) -> Result<usize, XdnaError> {
    shape
        .get(key)
        .copied()
        .ok_or_else(|| invalid(format!("missing {key} in {dir}/shape.txt")))
}

fn as_bytes(values: &[i8]) -> &[u8] {
    unsafe { std::slice::from_raw_parts(values.as_ptr().cast::<u8>(), values.len()) }
}

fn as_i32(values: &[u8]) -> &[i32] {
    unsafe {
        std::slice::from_raw_parts(
            values.as_ptr().cast::<i32>(),
            values.len() / size_of::<i32>(),
        )
    }
}

fn invalid(message: impl Into<String>) -> XdnaError {
    XdnaError::InvalidOpus(message.into())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn whole_array_constants_match_generated_r14_streams() {
        let w4 = Layout::for_mode(NpuWholeMode::W4);
        let w8 = Layout::for_mode(NpuWholeMode::W8);
        assert_eq!(w4.activation_bytes(), 6144);
        assert_eq!(w4.weight_bytes, 12288);
        assert_eq!(w8.activation_bytes(), 6144);
        assert_eq!(w8.weight_bytes, 12288);
        assert_eq!(w4.output_per_core(), 2304);
        assert_eq!(w8.output_per_core(), 1152);
        assert_eq!((w4.macro_m(), w4.macro_n()), (96, 384));
        assert_eq!((w8.macro_m(), w8.macro_n()), (96, 192));
    }

    #[test]
    fn parses_cache_shape_manifest() {
        let shape = parse_shape("m=256\nk=768\nn=768\nmm=3\nnm=2\nkg=3\nnblk=18\n");
        assert_eq!(shape.get("m"), Some(&256));
        assert_eq!(shape.get("nblk"), Some(&18));
    }
}
