//! rocprofv3 stats CSV parser and internal-vs-rocprof coverage cross-checker.
//!
//! rocprofv3 observes ALL kernels that execute on the GPU via the HSA queue.
//! The internal `HIPFIRE_PROFILE` tracker only sees kernels explicitly wrapped
//! with [`crate::profile::begin_timer`]. When a kernel is added without a timer,
//! rocprofv3 still records it but the internal profile misses it entirely
//! ("hidden lever" bug, 2026-05-19: `gemm_q8_0_batched` was 65% of A3B prefill
//! time and fully invisible).
//!
//! This module cross-checks both sources and surfaces "blindspots" -- kernels
//! rocprofv3 saw that the internal profile did not account for.
//!
//! # Zero hot-path overhead
//!
//! All work happens inside [`stop_with_rocprof`], which is called *after* the
//! benchmark completes to parse a CSV file. The hot path (kernel launches with
//! `profile::begin_timer`) is completely unchanged.
//!
//! # rocprofv3 stats CSV format
//!
//! Generated by:
//! ```sh
//! rocprofv3 --kernel-trace --stats -S -f csv -d <dir> -o <prefix> -- <cmd>
//! ```
//! File: `<dir>/<prefix>_kernel_stats.csv`
//! Columns: `Name,Calls,TotalDurationNs,AverageNs,Percentage,MinNs,MaxNs,StdDev`
//!
//! The `Name` field is the mangled kernel symbol (e.g.
//! `_Z22gemm_q8_0_batched_kernPKjPKfjS0_S2_ii.kd`). The internal profiler uses
//! short human-readable aliases (e.g. `"gemm_q8_0_batched"`). Matching uses
//! substring search: a rocprof entry is "covered" if any internal alias appears
//! as a substring of the rocprof `Name` (case-insensitive for robustness).

use crate::profile::{stop, ProfileEntry};
use std::path::Path;

/// A single kernel as reported by rocprofv3's `--stats` aggregate CSV.
#[derive(Debug, Clone)]
pub struct RocprofKernel {
    /// Mangled kernel symbol as rocprofv3 reports it (the `Name` CSV column).
    pub name: String,
    /// Total invocation count (the `Calls` CSV column).
    pub calls: u64,
    /// Total wall time in microseconds (TotalDurationNs / 1000).
    pub duration_us: f64,
    /// Percentage of total profiled GPU time (the `Percentage` CSV column).
    pub percent: f64,
}

/// Cross-check result: internal profile vs. rocprofv3 kernel trace.
#[derive(Debug)]
pub struct ProfileReport {
    /// Internal `HIPFIRE_PROFILE` entries collected via `profile::begin_timer`.
    pub internal: Vec<ProfileEntry>,
    /// All kernels rocprofv3 observed in the `_kernel_stats.csv`.
    pub rocprof: Vec<RocprofKernel>,
    /// rocprof entries with NO match in the internal profile (the hidden levers).
    pub blindspots: Vec<RocprofKernel>,
    /// Sum of all internal profile times (us).
    pub internal_total_us: f64,
    /// Sum of all rocprof kernel times (us). This is the ground-truth total.
    pub rocprof_total_us: f64,
    /// `(rocprof_total_us - blindspot_total_us) / rocprof_total_us * 100.0`.
    /// 100.0 means every kernel rocprof saw is accounted for internally.
    /// 0.0 means the rocprof CSV was absent or empty (check `rocprof.is_empty()`).
    pub coverage_pct: f64,
    /// Sum of blindspot kernel times (us) -- GPU time not visible to internal profiling.
    pub blindspot_total_us: f64,
}

/// Parse a rocprofv3 `_kernel_stats.csv` file into per-kernel aggregates.
///
/// Returns an error if the file cannot be read or the header is missing.
/// Malformed individual rows are silently skipped (with a stderr warning)
/// so a partial CSV does not abort a bench run.
///
/// The CSV may contain template kernel names with commas (e.g.
/// `kernel<int, float>`). The format has exactly 7 numeric tail columns, so
/// the `Name` field is reconstructed as everything before those 7 tail tokens.
pub fn parse_rocprof_stats_csv(path: &Path) -> Result<Vec<RocprofKernel>, String> {
    let text = std::fs::read_to_string(path)
        .map_err(|e| format!("rocprofv3 CSV read {}: {e}", path.display()))?;
    parse_rocprof_stats_csv_text(&text)
}

/// Parse the CSV text directly. Exposed as a separate function so tests can
/// feed synthetic CSV strings without touching the filesystem.
pub fn parse_rocprof_stats_csv_text(text: &str) -> Result<Vec<RocprofKernel>, String> {
    let mut lines = text.lines();

    // Validate and skip header line.
    let header = match lines.next() {
        Some(h) => h.trim().to_ascii_lowercase(),
        None => return Err("rocprofv3 CSV is empty".to_string()),
    };
    if !header.contains("name") || !header.contains("calls") {
        return Err(format!(
            "rocprofv3 CSV header does not look like kernel stats: {header:?}"
        ));
    }

    let mut kernels = Vec::new();
    for (line_no, raw) in lines.enumerate() {
        let line = raw.trim();
        if line.is_empty() {
            continue;
        }
        // Split by comma, then reconstruct Name from all but the last 7 tokens.
        let parts: Vec<&str> = line.split(',').collect();
        // Need at least 8 columns (1 name + 7 numeric).
        if parts.len() < 8 {
            eprintln!(
                "WARN rocprofv3 CSV line {}: expected >=8 columns, got {}; skipping",
                line_no + 2,
                parts.len()
            );
            continue;
        }
        let n = parts.len();
        // Last 7 are the numeric columns (Calls, TotalDurationNs, AverageNs,
        // Percentage, MinNs, MaxNs, StdDev). Name is everything before them.
        let name_raw = parts[..n - 7].join(",").trim().to_string();
        if name_raw.is_empty() {
            // Skip domain-level aggregate rows that have no kernel name.
            continue;
        }

        let calls_str = parts[n - 7].trim();
        let total_ns_str = parts[n - 6].trim();
        let _avg_ns_str = parts[n - 5].trim(); // parsed but unused
        let pct_str = parts[n - 4].trim();
        // MinNs, MaxNs, StdDev at n-3, n-2, n-1 -- not needed.

        let calls: u64 = match calls_str.parse() {
            Ok(v) => v,
            Err(e) => {
                eprintln!(
                    "WARN rocprofv3 CSV line {}: Calls parse error ({calls_str:?}): {e}; skipping",
                    line_no + 2
                );
                continue;
            }
        };
        let total_duration_ns: f64 = match total_ns_str.parse() {
            Ok(v) => v,
            Err(e) => {
                eprintln!(
                    "WARN rocprofv3 CSV line {}: TotalDurationNs parse error ({total_ns_str:?}): {e}; skipping",
                    line_no + 2
                );
                continue;
            }
        };
        let percent: f64 = match pct_str.parse() {
            Ok(v) => v,
            Err(e) => {
                eprintln!(
                    "WARN rocprofv3 CSV line {}: Percentage parse error ({pct_str:?}): {e}; skipping",
                    line_no + 2
                );
                continue;
            }
        };

        kernels.push(RocprofKernel {
            name: name_raw,
            calls,
            duration_us: total_duration_ns / 1_000.0,
            percent,
        });
    }
    Ok(kernels)
}

/// Cross-check internal profile entries against the rocprofv3 kernel stats.
///
/// Matching strategy: a rocprof entry is "covered" when any internal
/// `ProfileEntry.kernel` string is found as a case-insensitive substring of the
/// rocprof kernel `Name`. This handles the common case where the internal alias
/// (e.g. `"gemm_q8_0_batched"`) is embedded in the mangled C++ symbol name.
///
/// Exact-match is tried first; substring is the fallback. An internal entry
/// may cover multiple rocprof entries (e.g. multiple specializations of the
/// same base kernel).
pub fn compute_coverage(internal: &[ProfileEntry], rocprof: &[RocprofKernel]) -> ProfileReport {
    let internal_total_us: f64 = internal.iter().map(|e| e.time_us).sum();
    let rocprof_total_us: f64 = rocprof.iter().map(|k| k.duration_us).sum();

    // Build a lowercase set of all internal kernel names for O(1) lookup.
    let internal_names_lower: Vec<String> = internal
        .iter()
        .map(|e| e.kernel.to_ascii_lowercase())
        .collect();

    let mut blindspots = Vec::new();
    for rk in rocprof {
        let rk_lower = rk.name.to_ascii_lowercase();
        // Exact match first, then substring.
        let covered = internal_names_lower.iter().any(|alias| {
            // Exact (after lowercasing)
            rk_lower == *alias
            // Substring: mangled name contains the alias
            || rk_lower.contains(alias.as_str())
        });
        if !covered {
            blindspots.push(rk.clone());
        }
    }

    let blindspot_total_us: f64 = blindspots.iter().map(|k| k.duration_us).sum();
    let coverage_pct = if rocprof_total_us > 0.0 {
        (rocprof_total_us - blindspot_total_us) / rocprof_total_us * 100.0
    } else {
        0.0
    };

    ProfileReport {
        internal: internal.to_vec(),
        rocprof: rocprof.to_vec(),
        blindspots,
        internal_total_us,
        rocprof_total_us,
        coverage_pct,
        blindspot_total_us,
    }
}

/// Stop the internal profiler and cross-check against a rocprofv3 stats CSV.
///
/// Returns `None` if the internal profiler was not active (i.e., `profile::start()`
/// was never called). If the CSV file is absent or unreadable, a warning is
/// emitted to stderr but the function still returns `Some(report)` with an
/// empty `rocprof` list -- the internal data is not lost.
///
/// This function is only called after the benchmark completes; it has zero
/// overhead on the kernel hot path.
pub fn stop_with_rocprof(csv_path: &Path) -> Option<ProfileReport> {
    let internal = stop()?; // None if profiling was not active.

    let rocprof = match parse_rocprof_stats_csv(csv_path) {
        Ok(v) => v,
        Err(e) => {
            eprintln!("WARN rocprof CSV unavailable, internal-only profile: {e}");
            Vec::new()
        }
    };

    Some(compute_coverage(&internal, &rocprof))
}

// --- Tests ----------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // Synthetic _kernel_stats.csv: 3 kernels.
    // Internal profiler tracked "gemm_q8_0_batched" and "rmsnorm".
    // rocprofv3 saw:
    //   (1) _Z22gemm_q8_0_batched_kernPKjPKfjS0_S2_ii.kd -- matches via substring
    //   (2) _Z7rmsnormPfPKfS0_i.kd                       -- matches via substring
    //   (3) _Z22gemm_hfq4g256_residual_kd                 -- BLINDSPOT (no timer)
    const SYNTHETIC_CSV: &str = "\
Name,Calls,TotalDurationNs,AverageNs,Percentage,MinNs,MaxNs,StdDev
_Z22gemm_q8_0_batched_kernPKjPKfjS0_S2_ii.kd,640,348000000,543750,70.0,500000,600000,25000
_Z7rmsnormPfPKfS0_i.kd,100,50000000,500000,10.0,450000,550000,10000
_Z22gemm_hfq4g256_residual_kd,200,100000000,500000,20.0,480000,520000,8000
";

    #[test]
    fn test_parse_csv() {
        let kernels = parse_rocprof_stats_csv_text(SYNTHETIC_CSV).expect("parse ok");
        assert_eq!(kernels.len(), 3, "should parse 3 kernel rows");

        let k0 = &kernels[0];
        assert!(k0.name.contains("gemm_q8_0_batched"), "first kernel name");
        assert_eq!(k0.calls, 640);
        // TotalDurationNs = 348_000_000 ns -> 348_000 us
        assert!((k0.duration_us - 348_000.0).abs() < 1.0, "duration_us");
        assert!((k0.percent - 70.0).abs() < 0.01, "percent");
    }

    #[test]
    fn test_coverage_and_blindspot() {
        let kernels = parse_rocprof_stats_csv_text(SYNTHETIC_CSV).expect("parse ok");

        // Simulate two internal entries: one for gemm_q8_0_batched, one for rmsnorm.
        // ProfileEntry uses &'static str -- use string literals that match the test.
        let internal = vec![
            ProfileEntry {
                category: "linear",
                kernel: "gemm_q8_0_batched",
                time_us: 100_000.0, // internal sees less because batch has no timer
                bytes: 1024,
            },
            ProfileEntry {
                category: "norm",
                kernel: "rmsnorm",
                time_us: 40_000.0,
                bytes: 512,
            },
        ];

        let report = compute_coverage(&internal, &kernels);

        // internal_total_us
        assert!((report.internal_total_us - 140_000.0).abs() < 1.0);

        // rocprof_total_us = 348_000 + 50_000 + 100_000 = 498_000 us
        assert!((report.rocprof_total_us - 498_000.0).abs() < 1.0);

        // blindspots: only gemm_hfq4g256_residual (100_000 us) is a blindspot
        assert_eq!(report.blindspots.len(), 1, "exactly one blindspot");
        assert!(
            report.blindspots[0].name.contains("hfq4g256_residual"),
            "blindspot is the un-tracked kernel"
        );
        assert!((report.blindspot_total_us - 100_000.0).abs() < 1.0);

        // coverage_pct = (498_000 - 100_000) / 498_000 * 100 ~= 79.9%
        let expected_coverage = 398_000.0 / 498_000.0 * 100.0;
        assert!(
            (report.coverage_pct - expected_coverage).abs() < 0.1,
            "coverage_pct {:.2} ~= {:.2}",
            report.coverage_pct,
            expected_coverage
        );
    }

    #[test]
    fn test_empty_csv_header_only() {
        let text = "Name,Calls,TotalDurationNs,AverageNs,Percentage,MinNs,MaxNs,StdDev\n";
        let kernels = parse_rocprof_stats_csv_text(text).expect("header-only is ok");
        assert!(kernels.is_empty());
    }

    #[test]
    fn test_malformed_header_rejected() {
        let text = "not,a,valid,header\nfoo,1,1000,1000,50.0,900,1100,50\n";
        let result = parse_rocprof_stats_csv_text(text);
        assert!(result.is_err(), "should error on unrecognized header");
    }
}
